version: '3.8'

services: 
    database:
        build: ./SmartHome-Database
        volumes: 
            - database:/var/lib/postgresql/11/main
        ports:
            - 5432:5432
        env_file:
            - ./SmartHome-Database/.env
        container_name: database
    backend:
        build: ./SmartHome-Backend
        volumes: 
            - apps:/usr/src/app
        ports:
            - 8080:8000
        env_file: 
            - ./SmartHome-Backend/.env
        container_name: backend
        depends_on:
            - database
    frontend:
        build: ./SmartHome-FrontEnd
        volumes:
            - apps:/var/www
        ports: 
            - 5000:5000
        env_file:
            - ./SmartHome-FrontEnd/.env
        container_name: frontend
        depends_on:
            - backend
    tauron:
        build: ./SmartHome-TauronEMeter
        volumes: 
            - apps:/usr/src/app
        container_name: tauron
        depends_on:
            - backend
        tty: true
    solarman:
        build: ./SmartHome-SolarMan
        volumes: 
            - apps:/usr/src/app
        env_file:
            - ./SmartHome-SolarMan/.env
        container_name: solarman
        depends_on:
            - backend
        tty: true
volumes: 
    apps:
    database: